RULES_TEXT = (
    "Reglas basicas (ingles):\n"
    "1. Las oraciones completas suelen requerir sujeto explicito.\n"
    "   Ejemplo: 'It is raining.' (no: 'Is raining.')\n"
    "   Traduccion: 'Esta lloviendo.' (no: 'Esta lloviendo' sin sujeto en ingles)\n"
    "2. Las oraciones completas suelen requerir verbo.\n"
    "   Ejemplo: 'She studies English.' (no: 'She English.')\n"
    "   Traduccion: 'Ella estudia ingles.'\n"
    "3. En imperativos, el sujeto 'you' suele ser implicito.\n"
    "   Ejemplo: 'Sit down.' (= You sit down.)\n"
    "   Traduccion: 'Sientate.' (= Tu sientate.)\n"
    "4. Las preguntas suelen usar auxiliar (do/does/is/are, etc.).\n"
    "   Ejemplo: 'Do you like coffee?' / 'Is she at home?'\n"
    "   Traduccion: 'Te gusta el cafe?' / 'Ella esta en casa?'\n"
    "5. En presente simple, he/she/it suele llevar verbo con -s.\n"
    "   Ejemplo: 'He works here.' / 'She likes music.'\n"
    "   Traduccion: 'El trabaja aqui.' / 'A ella le gusta la musica.'\n"
    "6. Para negacion en presente simple se usa do/does + not + verbo base.\n"
    "   Ejemplo: 'I do not understand.' / 'He does not study on Sundays.'\n"
    "   Traduccion: 'No entiendo.' / 'El no estudia los domingos.'\n"
    "7. Con 'to be' no se usa do/does para preguntas o negaciones.\n"
    "   Ejemplo: 'She is happy.' / 'Is she happy?' / 'She is not happy.'\n"
    "   Traduccion: 'Ella esta feliz.' / 'Ella esta feliz?' / 'Ella no esta feliz.'\n"
    "8. Los articulos 'a/an' dependen del sonido inicial (no solo la letra).\n"
    "   Ejemplo: 'a book', 'an apple', 'an hour', 'a university'\n"
    "   Traduccion: 'un libro', 'una manzana', 'una hora', 'una universidad'\n"
    "9. El adjetivo normalmente va antes del sustantivo en ingles.\n"
    "   Ejemplo: 'a big house' (no: 'a house big')\n"
    "   Traduccion: 'una casa grande'\n"
    "10. El orden basico en afirmativas suele ser Sujeto + Verbo + Complemento.\n"
    "   Ejemplo: 'They play soccer after school.'\n"
    "   Traduccion: 'Ellos juegan futbol despues de la escuela.'\n"
    "11. Las preposiciones comunes no se traducen literal siempre.\n"
    "   Ejemplo: 'interested in', 'good at', 'depend on'\n"
    "   Traduccion: 'interesado en', 'bueno para/en', 'depender de'\n"
    "12. En pasado simple regular, muchos verbos terminan en -ed.\n"
    "   Ejemplo: 'I worked yesterday.' / 'They visited Madrid last year.'\n"
    "   Traduccion: 'Trabaje ayer.' / 'Ellos visitaron Madrid el ano pasado.'"
)


TENSES_TEXT = (
    "Tiempos verbales (ingles) con ejemplos:\n"
    "1. Presente simple (rutinas / hechos)\n"
    "   Estructura: Sujeto + verbo base (+s en he/she/it)\n"
    "   Ejemplo: 'I study every day.' / 'She works at a bank.'\n"
    "   Traduccion: 'Yo estudio todos los dias.' / 'Ella trabaja en un banco.'\n"
    "2. Presente continuo (ahora, en progreso)\n"
    "   Estructura: Sujeto + am/is/are + verbo-ing\n"
    "   Ejemplo: 'I am studying now.' / 'They are playing.'\n"
    "   Traduccion: 'Estoy estudiando ahora.' / 'Ellos estan jugando.'\n"
    "3. Pasado simple (acciones terminadas)\n"
    "   Estructura: Sujeto + verbo en pasado\n"
    "   Ejemplo: 'I visited my grandmother yesterday.'\n"
    "   Traduccion: 'Visite a mi abuela ayer.'\n"
    "4. Futuro con 'will' (decision/prediccion)\n"
    "   Estructura: Sujeto + will + verbo base\n"
    "   Ejemplo: 'I will call you tonight.'\n"
    "   Traduccion: 'Te llamare esta noche.'\n"
    "5. Futuro con 'going to' (plan/intencion)\n"
    "   Estructura: Sujeto + am/is/are + going to + verbo base\n"
    "   Ejemplo: 'We are going to travel next month.'\n"
    "   Traduccion: 'Vamos a viajar el proximo mes.'\n"
    "6. Presente perfecto (experiencia / resultado)\n"
    "   Estructura: Sujeto + have/has + participio pasado\n"
    "   Ejemplo: 'I have finished my homework.' / 'She has seen that movie.'\n"
    "   Traduccion: 'He terminado mi tarea.' / 'Ella ha visto esa pelicula.'\n"
    "7. Pasado continuo (accion en progreso en el pasado)\n"
    "   Estructura: Sujeto + was/were + verbo-ing\n"
    "   Ejemplo: 'I was sleeping when you called.'\n"
    "   Traduccion: 'Yo estaba durmiendo cuando llamaste.'\n"
    "8. Modales (can / should / must) usan verbo base\n"
    "   Ejemplo: 'She can swim.' / 'You should rest.' / 'We must leave now.'\n"
    "   Traduccion: 'Ella puede nadar.' / 'Deberias descansar.' / 'Debemos irnos ahora.'"
)


DEFAULT_MESSAGE = "Usa el menu para abrir el formulario y guardar una palabra con ejemplo."
